fix: fail with explicit message when --project-version is missing and using deptrack
Will fix https://github.com/CycloneDX/cdxgen/issues/256

Error message being displayed:

```
cdxgen -r -o bom.xml --server-url $DEPTRACK_HOST_URL --api-key $DEPTRACK_TOKEN --project-name MyProject --fail-on-error
Error: Missing --project-version, please specify one
    at exports.submitBom (<redacted>/node_modules/@cyclonedx/cdxgen/index.js:4291:11)
    at <redacted>/node_modules/@cyclonedx/cdxgen/bin/cdxgen:291:31
```

Signed-off-by: Pierre Souchay <pierre.souchay@axaclimate.com>